# Generated by Django 5.2 on 2025-05-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehablu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='subjectgrade',
            old_name='subject_name',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='credit_hours',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='user',
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
