# Generated by Django 5.2 on 2025-05-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehablu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herodashboard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='herodashboard',
            name='user',
        ),
        migrations.AddField(
            model_name='herodashboard',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='herodashboard',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='herodashboard',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
