# Generated by Django 5.2 on 2025-05-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehablu', '0002_remove_herodashboard_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DressBetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_name', models.CharField(max_length=100)),
                ('occasion', models.CharField(max_length=100)),
                ('style_tips', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearnNewSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resources', models.TextField(blank=True)),
            ],
        ),
    ]
