# Generated by Django 5.2 on 2025-05-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehablu', '0002_remove_herodashboard_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIChatViewSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField(default='Unknown', max_length=255)),
            ],
        ),
    ]
