# Generated by Django 5.2 on 2025-05-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehablu', '0003_openaichatviewset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenAIChatViewSet',
            new_name='OpenAIChat',
        ),
    ]
