# Generated by Django 5.2 on 2025-05-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehablu', '0004_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
            ],
        ),
    ]
