# Generated by Django 5.2 on 2025-05-05 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehablu', '0004_rename_openaichatviewset_openaichat'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaichat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openaichat',
            name='messages',
            field=models.TextField(),
        ),
    ]
