# Generated by Django 5.2 on 2025-05-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehablu', '0005_funfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('experience_points', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
