# Generated by Django 5.2 on 2025-05-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehablu', '0003_dressbetter_learnnewskill'),
        ('rehablu', '0006_marathon'),
    ]

    operations = [
    ]
